require "jc.options"
require "jc.keybindings"
require "jc.plugins"
require "jc.colorscheme"
require "jc.comment"
require "jc.nvimtree"
require "jc.cmp"
require "jc.lsp"
require "jc.treesitter"
require "jc.project"
require "jc.telescope"
require "jc.toggleterm"
require "jc.autocmds"
-- require "jc.startup"
--
